name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      continue-on-error: true
    
    - name: Run coverage
      run: npm run coverage
    
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.3.4
      with:
        path-to-lcov: coverage/lcov.info
